### ISSUE TITLE
han bombardeado el server

### ISSUE THREAD

**Issue by Aniolobolo** [Aniolobolo/Bubble-Bobble-WCG#1]
AYUDA HAN BOMBARDEADO CARACAS

**Comment by AsiGamer2** [comment]
Caracas sin maracas

**Comment by Aniolobolo** [comment]
FALSA alarma
![gato](https://github.com/Aniolobolo/cooking-mages-from-outer-dimension/assets/99729558/d40c60ab-3f7b-46c7-a521-92bc64854de5)
